apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo
  labels:
    provider: mongo
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: mongo
        name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
