apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
  labels:
    provider: postgresql
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: postgresql
    spec:
      containers:
      - name: postgres
        image: quay.io/galexrt/zulip-postgresql-tsearchextras:latest
        env:
        - name: DB_NAME
          value: zulip
        - name: DB_USER
          value: zulip
        - name: DB_PASS
          value: zulip
        ports:
        - containerPort: 5432
